version: '3'

services:
  nginx:
    container_name: nginx_req-res-log-sys
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./client-find-ui/dist:/usr/share/nginx/html/www # bind mount 会清空容器内的文件，挂载宿主机的文件。
  mongo:
    container_name: mongo_req-res-log-sys
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db # named volume 会把容器内的文件拷贝到宿主机上，同名文件以宿主机的为准。挂载位置一般在宿主机的 /var/lib/docker/volumes 目录里。
    ports:
      - 27017:27017
volumes:
  mongo-data:
